trigger:
  - master
pr:
  - master

resources:
  - repo: self
    clean: true
    fetchDepth: 1

steps:
  - task: PowerShell@2
    inputs:
      targetType: inline
      script: |
        $global:PesterDebugPreference_ShowFullErrors = $true
        Set-StrictMode -Version Latest
        Import-Module .\Pester.psd1
        Invoke-Pester -ExcludeTag VersionChecks, StyleRules, Help -EnableExit
      errorActionPreference: stop
      pwsh: true